apiVersion: v1
kind: PersistentVolume
metadata:
  name: vikram-pv1
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  storageClassName: standard
  hostPath:
    path: /vikram_PV_dir